# Form implementation generated from reading ui file 'c:\Users\grubg\Documents\KULIAH\Pemdes-W01\UAS\PEMESANAN_MAKANAN\src\ui\ErrorDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Error(object):
    def setupUi(self, Error_2):
        Error_2.setObjectName("Error_2")
        Error_2.resize(542, 170)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Error_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 521, 151))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.Error = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Error.sizePolicy().hasHeightForWidth())
        self.Error.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Error.setFont(font)
        self.Error.setWordWrap(True)
        self.Error.setObjectName("Error")
        self.verticalLayout.addWidget(self.Error)

        self.retranslateUi(Error_2)
        QtCore.QMetaObject.connectSlotsByName(Error_2)

    def retranslateUi(self, Error_2):
        _translate = QtCore.QCoreApplication.translate
        Error_2.setWindowTitle(_translate("Error_2", "Dialog"))
        self.label.setText(_translate("Error_2", "ERROR:"))
        self.Error.setText(_translate("Error_2", "Error Massage"))
