# Form implementation generated from reading ui file 'c:\Users\grubg\Documents\KULIAH\Pemdes-W01\UAS\PEMESANAN_MAKANAN\src\ui\kasir.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Kasir(object):
    def setupUi(self, Kasir):
        Kasir.setObjectName("Kasir")
        Kasir.resize(610, 591)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Kasir)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 591, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.kasir = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(28)
        self.kasir.setFont(font)
        self.kasir.setObjectName("kasir")
        self.verticalLayout.addWidget(self.kasir)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.idkasir = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.idkasir.setMinimumSize(QtCore.QSize(0, 40))
        self.idkasir.setObjectName("idkasir")
        self.horizontalLayout_2.addWidget(self.idkasir)
        self.namakasir = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.namakasir.setMinimumSize(QtCore.QSize(0, 40))
        self.namakasir.setObjectName("namakasir")
        self.horizontalLayout_2.addWidget(self.namakasir)
        self.filter = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.filter.setMinimumSize(QtCore.QSize(0, 40))
        self.filter.setObjectName("filter")
        self.horizontalLayout_2.addWidget(self.filter)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tableView = QtWidgets.QTableView(parent=self.verticalLayoutWidget)
        self.tableView.setMinimumSize(QtCore.QSize(0, 40))
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableView)
        self.SHOW_RECORD = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.SHOW_RECORD.setMinimumSize(QtCore.QSize(0, 40))
        self.SHOW_RECORD.setObjectName("SHOW_RECORD")
        self.verticalLayout.addWidget(self.SHOW_RECORD)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.UPDATE = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.UPDATE.setMinimumSize(QtCore.QSize(0, 40))
        self.UPDATE.setObjectName("UPDATE")
        self.horizontalLayout.addWidget(self.UPDATE)
        self.CANCEL = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.CANCEL.setMinimumSize(QtCore.QSize(0, 40))
        self.CANCEL.setObjectName("CANCEL")
        self.horizontalLayout.addWidget(self.CANCEL)
        self.DELETE = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.DELETE.setMinimumSize(QtCore.QSize(0, 40))
        self.DELETE.setObjectName("DELETE")
        self.horizontalLayout.addWidget(self.DELETE)
        self.ADD = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.ADD.setMinimumSize(QtCore.QSize(0, 40))
        self.ADD.setObjectName("ADD")
        self.horizontalLayout.addWidget(self.ADD)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Kasir)
        QtCore.QMetaObject.connectSlotsByName(Kasir)

    def retranslateUi(self, Kasir):
        _translate = QtCore.QCoreApplication.translate
        Kasir.setWindowTitle(_translate("Kasir", "Form"))
        self.kasir.setText(_translate("Kasir", "Kasir"))
        self.idkasir.setPlaceholderText(_translate("Kasir", "ID KASIR"))
        self.namakasir.setPlaceholderText(_translate("Kasir", "NAMA KASIR"))
        self.filter.setText(_translate("Kasir", "FILTER"))
        self.SHOW_RECORD.setText(_translate("Kasir", "SHOW RECORD"))
        self.UPDATE.setText(_translate("Kasir", "UPDATE"))
        self.CANCEL.setText(_translate("Kasir", "CANCEL"))
        self.DELETE.setText(_translate("Kasir", "DELETE"))
        self.ADD.setText(_translate("Kasir", "ADD"))
