# Form implementation generated from reading ui file 'c:\Users\grubg\Documents\KULIAH\Pemdes-W01\UAS\PEMESANAN_MAKANAN\src\ui\makananRecord.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(545, 493)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.MainLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.MainLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.MainLayout.setContentsMargins(0, 0, 0, 0)
        self.MainLayout.setObjectName("MainLayout")
        self.judul = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.judul.sizePolicy().hasHeightForWidth())
        self.judul.setSizePolicy(sizePolicy)
        self.judul.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.judul.setFont(font)
        self.judul.setObjectName("judul")
        self.MainLayout.addWidget(self.judul)
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelid = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelid.sizePolicy().hasHeightForWidth())
        self.labelid.setSizePolicy(sizePolicy)
        self.labelid.setObjectName("labelid")
        self.verticalLayout_2.addWidget(self.labelid)
        self.ID = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.ID.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ID.sizePolicy().hasHeightForWidth())
        self.ID.setSizePolicy(sizePolicy)
        self.ID.setMinimumSize(QtCore.QSize(0, 40))
        self.ID.setObjectName("ID")
        self.verticalLayout_2.addWidget(self.ID)
        self.verticalLayout_14.addLayout(self.verticalLayout_2)
        self.MainLayout.addLayout(self.verticalLayout_14)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.labelnama = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelnama.sizePolicy().hasHeightForWidth())
        self.labelnama.setSizePolicy(sizePolicy)
        self.labelnama.setObjectName("labelnama")
        self.verticalLayout_13.addWidget(self.labelnama)
        self.NAMA = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.NAMA.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NAMA.sizePolicy().hasHeightForWidth())
        self.NAMA.setSizePolicy(sizePolicy)
        self.NAMA.setMinimumSize(QtCore.QSize(0, 40))
        self.NAMA.setObjectName("NAMA")
        self.verticalLayout_13.addWidget(self.NAMA)
        self.MainLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.labelharga = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelharga.sizePolicy().hasHeightForWidth())
        self.labelharga.setSizePolicy(sizePolicy)
        self.labelharga.setObjectName("labelharga")
        self.verticalLayout_12.addWidget(self.labelharga)
        self.HARGA = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.HARGA.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.HARGA.sizePolicy().hasHeightForWidth())
        self.HARGA.setSizePolicy(sizePolicy)
        self.HARGA.setMinimumSize(QtCore.QSize(0, 40))
        self.HARGA.setObjectName("HARGA")
        self.verticalLayout_12.addWidget(self.HARGA)
        self.MainLayout.addLayout(self.verticalLayout_12)
        self.UPDATE = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.UPDATE.setMinimumSize(QtCore.QSize(0, 40))
        self.UPDATE.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.UPDATE.setObjectName("UPDATE")
        self.MainLayout.addWidget(self.UPDATE)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.FIRST = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FIRST.sizePolicy().hasHeightForWidth())
        self.FIRST.setSizePolicy(sizePolicy)
        self.FIRST.setMinimumSize(QtCore.QSize(0, 40))
        self.FIRST.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.FIRST.setObjectName("FIRST")
        self.horizontalLayout_2.addWidget(self.FIRST)
        self.PREV = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PREV.sizePolicy().hasHeightForWidth())
        self.PREV.setSizePolicy(sizePolicy)
        self.PREV.setMinimumSize(QtCore.QSize(0, 40))
        self.PREV.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.PREV.setObjectName("PREV")
        self.horizontalLayout_2.addWidget(self.PREV)
        self.NEXT = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NEXT.sizePolicy().hasHeightForWidth())
        self.NEXT.setSizePolicy(sizePolicy)
        self.NEXT.setMinimumSize(QtCore.QSize(0, 40))
        self.NEXT.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.NEXT.setObjectName("NEXT")
        self.horizontalLayout_2.addWidget(self.NEXT)
        self.LAST = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LAST.sizePolicy().hasHeightForWidth())
        self.LAST.setSizePolicy(sizePolicy)
        self.LAST.setMinimumSize(QtCore.QSize(0, 40))
        self.LAST.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.LAST.setObjectName("LAST")
        self.horizontalLayout_2.addWidget(self.LAST)
        self.MainLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.judul.setText(_translate("Dialog", "DATA MAKANAN RECORD"))
        self.labelid.setText(_translate("Dialog", "Makanan ID:"))
        self.labelnama.setText(_translate("Dialog", "Nama Makanan:"))
        self.labelharga.setText(_translate("Dialog", "Harga:"))
        self.UPDATE.setText(_translate("Dialog", "UPDATE"))
        self.FIRST.setText(_translate("Dialog", "FIRST"))
        self.PREV.setText(_translate("Dialog", "PREVIOUS"))
        self.NEXT.setText(_translate("Dialog", "NEXT"))
        self.LAST.setText(_translate("Dialog", "LAST"))
