# Form implementation generated from reading ui file 'c:\Users\grubg\Documents\KULIAH\Pemdes-W01\UAS\PEMESANAN_MAKANAN\src\ui\pembeli.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 529)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 631, 511))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.judul = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        self.judul.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.judul.setFont(font)
        self.judul.setObjectName("judul")
        self.verticalLayout.addWidget(self.judul)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.namapembeli = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.namapembeli.setMinimumSize(QtCore.QSize(0, 40))
        self.namapembeli.setStyleSheet("font-weight: bold;")
        self.namapembeli.setObjectName("namapembeli")
        self.horizontalLayout.addWidget(self.namapembeli)
        self.nomortelepon = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.nomortelepon.setMinimumSize(QtCore.QSize(0, 40))
        self.nomortelepon.setStyleSheet("font-weight: bold;")
        self.nomortelepon.setText("")
        self.nomortelepon.setObjectName("nomortelepon")
        self.horizontalLayout.addWidget(self.nomortelepon)
        self.filter = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.filter.setMinimumSize(QtCore.QSize(0, 40))
        self.filter.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.filter.setObjectName("filter")
        self.horizontalLayout.addWidget(self.filter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableView = QtWidgets.QTableView(parent=self.verticalLayoutWidget)
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout.addWidget(self.tableView)
        self.showrecord = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.showrecord.setMinimumSize(QtCore.QSize(0, 40))
        self.showrecord.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.showrecord.setObjectName("showrecord")
        self.verticalLayout.addWidget(self.showrecord)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.UPDATE = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.UPDATE.setMinimumSize(QtCore.QSize(0, 40))
        self.UPDATE.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.UPDATE.setObjectName("UPDATE")
        self.horizontalLayout_2.addWidget(self.UPDATE)
        self.CANCEL = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.CANCEL.setMinimumSize(QtCore.QSize(0, 40))
        self.CANCEL.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.CANCEL.setObjectName("CANCEL")
        self.horizontalLayout_2.addWidget(self.CANCEL)
        self.DELETE = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.DELETE.setMinimumSize(QtCore.QSize(0, 40))
        self.DELETE.setStyleSheet("background: #D91656;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.DELETE.setObjectName("DELETE")
        self.horizontalLayout_2.addWidget(self.DELETE)
        self.ADD = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.ADD.setMinimumSize(QtCore.QSize(0, 40))
        self.ADD.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.ADD.setObjectName("ADD")
        self.horizontalLayout_2.addWidget(self.ADD)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.judul.setText(_translate("Form", "PEMBELI"))
        self.namapembeli.setPlaceholderText(_translate("Form", "NAMA PEMBELI"))
        self.nomortelepon.setPlaceholderText(_translate("Form", "NOMOR TELEPON"))
        self.filter.setText(_translate("Form", "FILTER"))
        self.showrecord.setText(_translate("Form", "SHOW RECORD"))
        self.UPDATE.setText(_translate("Form", "UPDATE"))
        self.CANCEL.setText(_translate("Form", "CANCEL"))
        self.DELETE.setText(_translate("Form", "DELETE"))
        self.ADD.setText(_translate("Form", "ADD"))
