# Form implementation generated from reading ui file 'c:\Users\grubg\Documents\KULIAH\Pemdes-W01\UAS\PEMESANAN_MAKANAN\src\ui\pembelirecord.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(558, 462)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 551, 442))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.record = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.record.sizePolicy().hasHeightForWidth())
        self.record.setSizePolicy(sizePolicy)
        self.record.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.record.setFont(font)
        self.record.setObjectName("record")
        self.verticalLayout.addWidget(self.record)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelID = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelID.sizePolicy().hasHeightForWidth())
        self.labelID.setSizePolicy(sizePolicy)
        self.labelID.setMinimumSize(QtCore.QSize(0, 40))
        self.labelID.setObjectName("labelID")
        self.verticalLayout_2.addWidget(self.labelID)
        self.IDPEMBELI = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.IDPEMBELI.setEnabled(False)
        self.IDPEMBELI.setMinimumSize(QtCore.QSize(0, 40))
        self.IDPEMBELI.setObjectName("IDPEMBELI")
        self.verticalLayout_2.addWidget(self.IDPEMBELI)
        self.labelnama = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelnama.sizePolicy().hasHeightForWidth())
        self.labelnama.setSizePolicy(sizePolicy)
        self.labelnama.setMinimumSize(QtCore.QSize(0, 40))
        self.labelnama.setObjectName("labelnama")
        self.verticalLayout_2.addWidget(self.labelnama)
        self.nama = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.nama.setMinimumSize(QtCore.QSize(0, 40))
        self.nama.setObjectName("nama")
        self.verticalLayout_2.addWidget(self.nama)
        self.labelnomortlp = QtWidgets.QLabel(parent=self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelnomortlp.sizePolicy().hasHeightForWidth())
        self.labelnomortlp.setSizePolicy(sizePolicy)
        self.labelnomortlp.setMinimumSize(QtCore.QSize(0, 40))
        self.labelnomortlp.setObjectName("labelnomortlp")
        self.verticalLayout_2.addWidget(self.labelnomortlp)
        self.nomortlp = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.nomortlp.setMinimumSize(QtCore.QSize(0, 40))
        self.nomortlp.setObjectName("nomortlp")
        self.verticalLayout_2.addWidget(self.nomortlp)
        self.UPDATE = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.UPDATE.setMinimumSize(QtCore.QSize(0, 40))
        self.UPDATE.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.UPDATE.setObjectName("UPDATE")
        self.verticalLayout_2.addWidget(self.UPDATE)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.first = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.first.setMinimumSize(QtCore.QSize(0, 40))
        self.first.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.first.setObjectName("first")
        self.horizontalLayout.addWidget(self.first)
        self.previous = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.previous.setMinimumSize(QtCore.QSize(0, 40))
        self.previous.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.previous.setObjectName("previous")
        self.horizontalLayout.addWidget(self.previous)
        self.next = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.next.setMinimumSize(QtCore.QSize(0, 40))
        self.next.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.next.setObjectName("next")
        self.horizontalLayout.addWidget(self.next)
        self.last = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.last.setMinimumSize(QtCore.QSize(0, 40))
        self.last.setStyleSheet("background: #22177A;\n"
"color: white;\n"
"font-weight: bold;\n"
"border: none;\n"
"padding-left: 20px;\n"
"padding-right: 20px;\n"
"border-radius: 4px;")
        self.last.setObjectName("last")
        self.horizontalLayout.addWidget(self.last)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.record.setText(_translate("Dialog", "PEMBELI RECORD"))
        self.labelID.setText(_translate("Dialog", "ID PEMBELI:"))
        self.labelnama.setText(_translate("Dialog", "NAMA PEMBELI:"))
        self.labelnomortlp.setText(_translate("Dialog", "NOMOR TELEPON:"))
        self.UPDATE.setText(_translate("Dialog", "UPDATE"))
        self.first.setText(_translate("Dialog", "FIRST"))
        self.previous.setText(_translate("Dialog", "PREVIOUS"))
        self.next.setText(_translate("Dialog", "NEXT"))
        self.last.setText(_translate("Dialog", "LAST"))
